# PostgreSQL. Versions 10.x and up are supported.
#
default: &default
  adapter: postgres
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pi_control_development
  url: postgres://postgres:mysecretpassword@localhost:5433

test:
  <<: *default
  database: pi_control_test
  url: postgres://postgres:mysecretpassword@localhost:5433

production:
  <<: *default
  database: pi_control_production
  url: postgres://postgres@localhost
